pipeline:
  identifier: Build_grafana_sqlite_to_postgres_1693965988717
  name: Build grafana-sqlite-to-postgres
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1693965905748
        repoName: wbh1/grafana-sqlite-to-postgres
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:1.18
                    shell: Sh
                    command: make build-all
                  timeout: ""
                  type: Run
                  when:
                    stageStatus: Success
              - step:
                  type: Plugin
                  name: publish_release
                  identifier: publish_release
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/github-release
                    settings:
                      api_key: <+secrets.getValue("github_api_key")>
                      files: dist/*
                  when:
                    stageStatus: Success
                    condition: <+codebase.tag> != null
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
